<?php

namespace AppBundle\Repository;

/**
 * OrderBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderBookRepository extends \Doctrine\ORM\EntityRepository
{
}
